In [82]:
import numpy as np
print(np.__version__)

2.2.4


In [83]:
a = np.array(10)#odimensional array
print(a)

10


In [84]:
a1 =np.array([10,20])#1d
#indexing
print(a1[0:1])

[10]


In [85]:
a2=np.array([[10,21],[20,30]])#2d
a2[0][1]

np.int64(21)

In [86]:
print(a2)

[[10 21]
 [20 30]]


In [87]:
a3 = np.array([[[10,20,30],[10,20,30]],[[50,60,80],[20,50,60]]])#3dimensional array
print(a3)

[[[10 20 30]
  [10 20 30]]

 [[50 60 80]
  [20 50 60]]]


In [88]:
print(a3[0][1][2])#three dimensional


30


In [89]:
a=([[11,12,],[15,16]])
b=np.asarray(a,dtype=float)
print(b)

[[11. 12.]
 [15. 16.]]


# row major order("c")///coloum major order("f")

In [90]:

b=np.asarray(a,dtype=int,order="c")
for i in np.nditer(b):
    print(i)

11
12
15
16


In [91]:
b=np.asarray(a,dtype=int,order="F")
for i in np.nditer(b):
    print(i)

11
15
12
16


In [92]:
a=b"welcome to numpy"
np.frombuffer(a,dtype="S1",count=2)


array([b'w', b'e'], dtype='|S1')

In [93]:
a=b"welcome to numpy"
np.frombuffer(a,dtype="S1",offset=5)

array([b'm', b'e', b' ', b't', b'o', b' ', b'n', b'u', b'm', b'p', b'y'],
      dtype='|S1')

In [94]:
a=[12.14,15]
np.fromiter(a,dtype="S1")

array([b'1', b'1'], dtype='|S1')

# Creating a NumPy array of zeros with a size of 3

In [95]:

a = np.zeros(3)
print(a)

[0. 0. 0.]


In [96]:
a = np.zeros([2, 2, 3])
print(a)

[[[0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]]]


In [97]:
a = np.full([2, 2, 3],2)
print(a)

[[[2 2 2]
  [2 2 2]]

 [[2 2 2]
  [2 2 2]]]


# Creating a 3D NumPy array of random with dimensions 2x2x3

In [98]:
a = np.random.rand(2, 2, 3)
print(a)

[[[0.59032676 0.87808282 0.0154372 ]
  [0.98862898 0.29682108 0.36390242]]

 [[0.67316761 0.16290685 0.99361503]
  [0.263552   0.22782144 0.63036094]]]


In [99]:
a = np.ones([2, 2, 3])
print(a)

[[[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]]


In [100]:
a = np.eye(4)
print(a)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [101]:
a1=np.array([[2,3],[1,3]])
a2=np.array([[4,5],[7,8]])
a1plus2=a1+a2
a1plus2

array([[ 6,  8],
       [ 8, 11]])

In [102]:
a1min2=a1-a2
a1min2

array([[-2, -2],
       [-6, -5]])

In [103]:
a1mul2=a1*a2
a1mul2

array([[ 8, 15],
       [ 7, 24]])

In [104]:
a1=np.array([[2,3],[1,3]])
a2=np.array([[4,5],[7,8]])
a1dot2=np.dot(a1,a2)
a1dot2

array([[29, 34],
       [25, 29]])

In [105]:
a1=np.array([[2,3],[1,3]])
a2=np.array([[4,5,4],[7,8,2]])
a1dot2=np.dot(a1,a2)
a1dot2

array([[29, 34, 14],
       [25, 29, 10]])

In [106]:
print("Matrix a2=", a2)
print("Transpose of matrix a2=", np.transpose(a2))

Matrix a2= [[4 5 4]
 [7 8 2]]
Transpose of matrix a2= [[4 7]
 [5 8]
 [4 2]]


In [110]:
arr1 = np.arange(4, dtype = np.float64).reshape(2, 2)
print('First array:') 
print(arr1)
print('\nSecond array:') 
arr2 = np.array([12, 12]) 
print(arr2)

print('\nAdding the two arrays:') 
print(np.add(arr1, arr2))

print('\nMultiplying the two arrays:')
print(np.multiply(arr1, arr2))

print('\nAfter applying reciprocal function:') 
print((np.reciprocal(arr2)))


print('\nApplying power function:') 
print(np.power(arr2, 2))

First array:
[[0. 1.]
 [2. 3.]]

Second array:
[12 12]

Adding the two arrays:
[[12. 13.]
 [14. 15.]]

Multiplying the two arrays:
[[ 0. 12.]
 [24. 36.]]

After applying reciprocal function:
[0 0]

Applying power function:
[144 144]


In [111]:
arr = np.array([5, 15, 20]) 
arr1 = np.array([2, 5, 9]) 
 
print('First array:') 
print(arr) 
 
print('\nSecond array:') 
print(arr1)
 
print('\nApplying mod() function:') 
print(np.mod(arr, arr1))
 
print('\nApplying remainder() function:') 
print(np.remainder(arr, arr1))

First array:
[ 5 15 20]

Second array:
[2 5 9]

Applying mod() function:
[1 0 2]

Applying remainder() function:
[1 0 2]
